project_panel/dashboard/urls.py
from django.urls import path, include
from .views import CustomerPanel, home, ExecutivePanel, AddProject, ProjectDetailsView, assign_task, finish_task

app_name = 'dashboard'

urlpatterns = [
    path('', home, name="home"),
    path('customer-panel/',  CustomerPanel.as_view(), name="customer_panel"),
    path('executive-panel/', ExecutivePanel.as_view(), name="executive_panel"),
    path('new-project/', AddProject.as_view(), name="new_project"),
    path('project-details/<int:project_id>/', ProjectDetailsView.as_view(), name="project_details"),
    path('tasks/assign/<int:task_id>/', assign_task, name='assign_task'),
    path('tasks/finish/<int:task_id>/', finish_task, name='finish_task'),
]

project_panel/project_panel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('registration.urls')),
    path('', include('dashboard.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project_panel/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from registration.models import UserDashboard


class Status(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=100, null=False, verbose_name="Nazwa projektu")
    customer = models.ForeignKey(UserDashboard, on_delete=models.CASCADE, verbose_name="Klient", related_name="customer")
    executors = models.ManyToManyField(UserDashboard, verbose_name="Wykonawca/y", related_name="executors")
    description = models.TextField(verbose_name="Opis projektu")
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    paid = models.BooleanField(default=False)
    status = models.ForeignKey(Status, default=1, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.title

    def get_all_tasks(self):
        return Task.objects.filter(project=self)


class Task(models.Model):
    title = models.CharField(max_length=100, null=False, verbose_name= "Nazwa zadania")
    spent_time = models.TimeField(verbose_name="Czas realizacji [h]", null=True, blank=True)
    status = models.ForeignKey(Status, default=1, on_delete=models.DO_NOTHING)
    executor = models.ForeignKey(UserDashboard, null=True, blank=True, on_delete=models.DO_NOTHING)
    project = models.ForeignKey(Project, on_delete=models.DO_NOTHING)
    price_per_hour = models.PositiveSmallIntegerField(null=True, blank=True)

    def __str__(self):
        return self.title

project_panel/dashboard/forms.py
from django.forms import ModelForm
from .models import Project
from django import forms
from django.contrib.auth.models import User
from registration.models import UserDashboard


class ProjectForm(ModelForm):
    all_executors = UserDashboard.get_all_executors()
    executors = forms.ModelMultipleChoiceField(queryset=all_executors, widget=forms.CheckboxSelectMultiple(),
                                               label="Wybierz wykonawców", required=True)

    class Meta:
        model = Project
        fields = ['title', 'description', 'executors']

project_panel/dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from registration.models import UserDashboard
from django.views.generic import TemplateView, View
from .models import Project, Task, Status
from .forms import ProjectForm
from django.contrib import messages


def home(request):
    if request.user.is_authenticated:
        logged_user = UserDashboard.objects.get(user=request.user)
        if logged_user.is_executive():
            return redirect('dashboard:executive_panel')
        else:
            return redirect('dashboard:customer_panel')
    return render(request, 'dashboard/home.html')


class ExecutivePanel(TemplateView):
    template_name = 'dashboard/executive_panel.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        logged_executor = UserDashboard.objects.get(user=self.request.user)
        all_projects = Project.objects.filter(executors=logged_executor)
        status_executing = Status.objects.get(id=2)
        list_of_tasks = []
        for project in all_projects:
            tasks = Task.objects.filter(project=project)
            for task in tasks:
                list_of_tasks.append(task)
                if task.executor == logged_executor and task.status == status_executing:
                    context['busy_executor'] = True

        context['list_of_tasks'] = list_of_tasks
        context['user_dashboard'] = logged_executor
        return context


class CustomerPanel(TemplateView):
    template_name = 'dashboard/customer_panel.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        logged_customer = UserDashboard.objects.get(user=self.request.user)
        context['all_projects'] = Project.objects.filter(customer=logged_customer)
        context['user_dashboard'] = logged_customer
        return context


class AddProject(View):
    template_name = 'dashboard/project_form.html'
    project_form_class = ProjectForm
    permission_required = [ 'dashboard.add_project' ]

    def get(self, request):
        project_form = self.project_form_class(None)
        return render(request, self.template_name, {'project_form': project_form})

    def post(self, request):
        project_form = self.project_form_class(request.POST)
        if project_form.is_valid():

            new_project = project_form.save(commit=False)
            logged_customer = UserDashboard.objects.get(user=request.user)
            new_project.customer = logged_customer
            new_project.save()

            # Tworzenie i przypisywanie tesków do Projektu
            for key_from_form in request.POST.keys():
                if 'task' in key_from_form:
                    new_task = Task(title=request.POST.get(key_from_form), project=new_project)
                    new_task.save()

            if not Task.objects.filter(project=new_project):
                startup_task_for_project_without_given_tasks = Task(
                    title='Startowe - stworzone przez system',
                    project=new_project)
                startup_task_for_project_without_given_tasks.save()

            # Przypisywanie wybranych wykonawców do Projektu
            for selected_executor in project_form.cleaned_data['executors']:
                new_project.executors.add(selected_executor)
            messages.info(request, "Projekt został pomyślnie dodany")
            return redirect('dashboard:home')
        else:
            return redirect('dashboard:new_project')


class ProjectDetailsView(View):
    template_name = 'dashboard/project_details.html'

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['project_id'])
        executors = project.executors.all()
        tasks = Task.objects.filter(project=project)
        context = {'project': project,
                   'executors': executors,
                   'tasks': tasks}
        return render(request, self.template_name, context)


def assign_task(request, task_id):
    logged_executor = UserDashboard.objects.get(user=request.user)

    for task in Task.objects.filter(executor=logged_executor):
        if task.status == 2:
            messages.info(request, "Możesz mieć zarezerwowane maksymalnie jedno zadanie.")
            return redirect('dashboard:home')

    task_to_assign = get_object_or_404(Task, id=task_id)
    task_to_assign.executor = logged_executor
    status_executing = Status.objects.get(id=2)
    task_to_assign.status = status_executing
    task_to_assign.save()
    project = get_object_or_404(Project, id=task_to_assign.project.id)
    project.status = status_executing
    project.save()
    messages.info(request, "Pomyślnie zarezerwowałeś zadanie.")

    return redirect('dashboard:home')


def finish_task(request, task_id):
    task_to_finish = get_object_or_404(Task, id=task_id)
    status_finish = Status.objects.get(id=3)
    task_to_finish.status = status_finish
    task_to_finish.save()

    project = get_object_or_404(Project, id=task_to_finish.project.id)
    project_all_tasks = Task.objects.filter(project=project)
    is_project_complete = True

    for task in project_all_tasks:
        if task.status != status_finish:
            is_project_complete = False
            break

    if is_project_complete:
        project.status = status_finish
        project.save()
        messages.info(request, "Projekt został zakończony.")

    messages.info(request, "Pomyślnie zakończyłeś zadanie.")
    return redirect('dashboard:home')

project_panel/templates/dashboard/customer_panel.html
{% extends 'base.html' %}

{% block title %} PANEL KLIENTA {% endblock %}

{% block extra_head %}
{% endblock %}

{% block jumbotron %}Panel Klienta{% endblock %}

{% block content %}

<div style="width:50%;" class="text-left">
<div id="user_info">
    <table class="table table-sm">
        <tr class="table-active">
            <th colspan="2">Moje dane</th>
        </tr>
        <tr>
            <td>Imie i nazwisko:  </td>
            <td>{{ user_dashboard.name }}</td>
        </tr>
        <tr>
            <td>Podmiot:  </td>
            <td>{{ user_dashboard.company_name }}</td>
        </tr>
        <tr>
            <td>Nip:  </td>
            <td>{{ user_dashboard.nip }}</td>
        </tr>
        <tr>
            <td>Adres pocztowy:  </td>
            <td>{{ user_dashboard.postal_address }}</td>
        </tr>
        <tr>
            <td>Telefon:  </td>
            <td>{{ user_dashboard.telephone }}</td>
        </tr>
    </table>
    </div>


<div id="projects_info" class="pt-4">
    <h4>Lista moich projektów</h4>
    {% if all_projects %}
    <table class="table table-sm">
        <tr class="table-active">
            <th scope="col">Nazwa projektu</th>
            <th scope="col">Status</th>
        </tr>
        {% for project in all_projects %}
            <tr>
                <td><a href="{% url 'dashboard:project_details' project.id %}">{{ project }}</a></td>
                <td>{{ project.status }}</td>
            </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>Nie posiadasz jeszcze żadnych projektów.</p>
    {% endif %}
</div>
<a href="{% url 'dashboard:new_project' %}"><input class="mb-3 mt-3 btn btn-primary" type="button" value="Dodaj projekt"></a>
</div>
{% endblock %}

project_panel/templates/dashboard/executive_panel.html
{% extends 'base.html' %}

{% block title %} PANEL WYKONAWCY {% endblock %}

{% block extra_head %}
{% endblock %}

{% block jumbotron %}Panel Wykonawcy{% endblock %}

{% block content %}

<div style="width:50%;" class="text-left">
{% if list_of_tasks %}
    <table class="table table-sm">
            <tr class="table-active">
                <th scope="col">Zadanie</th>
                <th scope="col">Z projektu</th>
                <th scope="col">Status</th>
                <th scope="col">Przypisanie do</th>
            </tr>
        {% for task in list_of_tasks %}
            <tr>
                <td>{{ task.title }}</td>
                <td><a href="{% url 'dashboard:project_details' task.project.id %}">{{ task.project }}</a></td>
                <td>{{ task.status }}</td>

                {% if task.executor is None %}
                    <td></td>
                {% else %}
                <td>{{ task.executor }}</td>
                {% endif %}

                {% if busy_executor %}
                    {% if task.status.name == "W trakcie" and task.executor.id == user.id %}
                        <td><a href="{% url 'dashboard:finish_task' task.id %}" class="btn btn-success p-2">Zakończ</a></td>
                    {% endif %}
                {% elif task.status.name == "Zaplanowany" %}
                    <td><a href="{% url 'dashboard:assign_task' task.id %}" class="btn btn-success p-2">Rezerwuj</a></td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>Nie zostałeś jeszcze przypisany do żadnych projektów.</p>
{% endif %}
</div>
{% endblock %}

project_panel/templates/dashboard/home.html
{% extends 'base.html' %}

{% block title %} PROJECT_PANEL {% endblock %}

{% block extra_head %}
{% endblock %}

{% block content %}
<h3>Jest to aplikacja do zarządzania projektami.</h3>
{% endblock %}

project_panel/templates/dashboard/project_details.html
{% extends 'base.html' %}

{% block title %} PROJEKT - {{ project.title }} {% endblock %}

{% block extra_head %}

{% endblock %}

{% block jumbotron %}PROJEKT - {{ project.title }}{% endblock %}

{% block content %}

<div style="width:50%;" class="text-left">
<div id="project_info">
    <p><a class="text-info no_hover_effect">Status: </a> {{ project.status }}</p>
    <p><a class="text-info no_hover_effect">Opis: </a>{{ project.description }}</p>
    <h4 class="pt-4">Wykonawcy:</h4>
    <ul id="id_executors">
        {% for executor in executors %}
        <li>
            {{ executor }}
        </li>
        {% endfor %}
    </ul>

    <h4 class="pt-4">Zadania:</h4>
    <table class="table table-sm">
        <tr class="table-active">
            <td>Zadanie</td>
            <td>Status</td>
            <td>Wykonuje</td>
        </tr>
        {% for task in tasks %}
            <tr>
                <td><a>{{ task }}</a></td>
                <td>{{ task.status }}</td>
                {% if task.executor is None %}
                    <td></td>
                {% else %}
                <td>{{ task.executor }}</td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
    <p><a href="{% url 'dashboard:home' %}" class="btn btn-secondary mt-5">Wróć</a></p>
</div>
</div>
{% endblock %}

project_panel/templates/dashboard/project_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load static %}

{% block title %} Formularz projektu {% endblock %}

{% block extra_head %}
<script src="{% static 'project_form.js' %}" type="text/javascript"></script>
{% endblock %}

{% block jumbotron %}FORMULARZ PROJEKTU{% endblock %}

{% block content %}

<div style="width:50%;" class="text-left">
    <form method="post" id="main_form">
        {% csrf_token %}
        {{ project_form|bootstrap }}

        <h3>Lista zadań:</h3>
            <input id="input_task" type="text" class="form-control-sm mr-sm-2">
            <input id="submit_task" type="button" value="Dodaj" class="btn btn-outline-primary p-1">
            <ul id="task_list">
            </ul>


        <input type="submit" value="Zapisz projekt" class="btn btn-primary mt-5">
    </form>
    <p><a href="{% url 'dashboard:home' %}" class="btn btn-secondary">Wróć</a></p>
</div>


{% endblock %}