project_panel/dashboard/urls.py
from django.urls import path, include
from .views import CustomerPanel, home, ExecutivePanel, AddProject, ProjectDetailsView, assign_task, finish_task

app_name = 'dashboard'

urlpatterns = [
    path('', home, name="home"),
    path('customer-panel/',  CustomerPanel.as_view(), name="customer_panel"),
    path('executive-panel/', ExecutivePanel.as_view(), name="executive_panel"),
    path('new-project/', AddProject.as_view(), name="new_project"),
    path('project-details/<int:project_id>/', ProjectDetailsView.as_view(), name="project_details"),
    path('tasks/assign/<int:task_id>/', assign_task, name='assign_task'),
    path('tasks/finish/<int:task_id>/', finish_task, name='finish_task'),
]

project_panel/project_panel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('registration.urls')),
    path('', include('dashboard.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project_panel/registration/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'registration'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

project_panel/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block extra_head %}{% endblock %}
    <script src="https://kit.fontawesome.com/4b2f9e7a5a.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'my_own.css' %}" type="text/css">
</head>
<body>




<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'dashboard:home' %}"><h1>PROJECT_PANEL</h1></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <form class="form-inline my-2 my-lg-0">
        {% if not user.is_authenticated %}
            <a class="pr-3 no_hover_effect">Zaloguj się, aby użyć aplikacji!</a>
            <a class="pr-3" href="{% url 'registration:login' %}"><i class="fas fa-sign-in-alt"></i> Zaloguj</a>
            <a href="{% url 'registration:register' %}"><i class="fas fa-user-plus"></i> Zarejestruj</a>
        {% else %}
        <a class="pr-3 no_hover_effect">Zalogowany - {{ user.first_name }}</a>
            <a href="{% url 'registration:logout' %}"><i class="fas fa-sign-out-alt"></i> Wyloguj</a>
        {% endif %}
    </form>
  </div>
</nav>


<div align="center">


<div class="jumbotron">
    <div class="container">
        <h1 class="display-4">{% block jumbotron %}Strona główna{% endblock %}</h1>
    </div>
</div>



{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <div class="alert alert-success" role="alert">
          {{ message }}
        </div>
    {% endfor %}
</ul>
{% endif %}

{% block content %}{% endblock %}

<hr style="height:1px; border-width:0; color:gray; background-color:gray;">

<footer class="page-footer font-small cyan darken-3 bottom mt-5">

  <div class="container">
    <div class="row">

      <div class="col-md-12 py-12">
        <div class="mb-6 flex-center">

          <a class="fb-ic">
              <a href="https://www.facebook.com/dominik.kopaczek/"><i class="fab fa-facebook-f fa-lg white-text mr-md-6 mr-3 fa-2x"> </i></a>
          </a>
          <a class="li-ic">
              <a href="https://www.instagram.com/dominikkopaczek/"><i class="fab fa-linkedin-in fa-lg white-text mr-md-6 mr-3 fa-2x"> </i></a>
          </a>
          <a class="ins-ic">
              <a href="https://www.linkedin.com/in/dominik-kopaczek/"><i class="fab fa-instagram fa-lg white-text mr-md-6 mr-3 fa-2x"> </i></a>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-copyright text-center py-3">
    Made by <a href="#">www.kopaczek.net
    <img class="pl-2" width="4%" height="4%" src="{% static 'dk-logo.png' %}" alt="Dominik Kopaczek logo"></a>
  </div>

</footer>

</div>
</body>
</html>